version: '3.8'

services:
  collector:
    build:
      context: collector
      dockerfile: Dockerfile
    volumes:
      - ./collector/crystaldba-collector.conf:/usr/local/crystaldba/share/collector/collector.conf:ro
    depends_on:
      - crystaldba-agent
    networks:
      - crystaldba_network
    environment:
      - COLLECTOR_API_URL=http://crystaldba-agent:7080
