collector_name: crystal_pg_stat_io
# Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
min_interval: 0s

metrics:
  - metric_name: crystal_pg_stat_io
    type: gauge
    help: 'Snapshots from pg_stat_io'
    key_labels:
      - backend_type
      - object
      - context
    value_label: crystal_metric
    values:
      - reads
      - writes
      - op_bytes
    query_ref: query_stat_io

queries:
  - query_name: query_stat_io
    query: |
      /* crystal-query */ SELECT
        backend_type,
        object,
        context,
        reads,
        writes,
        op_bytes
      FROM
        pg_stat_io
