collector_name: crystal_workload
# Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
min_interval: 0s

metrics:
  - metric_name: crystal_pg_stat_statements
    type: gauge
    help: 'Snapshots of pg_stat_statements'
    key_labels:
      - userid
      - dbid
      - datname
      - queryid
      - query
    value_label: crystal_metric
    values:
      - calls
      - total_exec_time
      - total_plan_time
      - rows
    query_ref: pg_stat_statements_query

  - metric_name: crystal_pg_stat_activity
    type: gauge
    help: 'Snapshots of pg_stat_activity'
    key_labels:
      - pid
      - application_name
      - datname
      - client_addr
      - client_hostname
      - client_port
      - backend_type
      - query_id
      - query
      - usename
      - wait_event_type
      - wait_event
      - state
    values:
      - num_backends
    query_ref: crystal_pg_stat_activity_query

  - metric_name: crystal_pg_stat_database
    type: gauge
    help: 'Snapshots of pg_stat_database'
    key_labels:
      - datid
      - datname
    value_label: crystal_metric
    values:
      - numbackends
      - xact_commit
      - xact_rollback
      - blks_read
      - blks_hit
      - tup_returned
      - tup_fetched
      - tup_inserted
      - tup_updated
      - tup_deleted
      - conflicts
      - temp_files
      - temp_bytes
      - deadlocks
      - checksum_failures
      - blk_read_time
      - blk_write_time
      - session_time
      - active_time
      - idle_in_transaction_time
      - sessions
      - sessions_abandoned
      - sessions_fatal
      - sessions_killed
      - size
    query_ref: crystal_pg_stat_database_query

  - metric_name: crystal_schema_disk_usage
    type: gauge
    help: 'Disk usage by schema'
    key_labels:
      - schema_name
    values:
      - size
    query_ref: crystal_schema_disk_usage_query

  - metric_name: crystal_table_disk_usage
    type: gauge
    help: 'Disk usage by table and index'
    key_labels:
      - schema_name
      - table_name
    value_label: crystal_metric
    values:
      - total_size
      - table_size
      - index_size
      - toast_size
    query_ref: crystal_table_disk_usage_query

queries:
  - query_name: crystal_pg_stat_activity_query
    query: |
      /* crystal-query */ SELECT
        a.pid,
        a.datname,
        a.client_addr,
        a.client_hostname,
        a.client_port,
        a.application_name,
        a.backend_type,
        a.query_id,
        lower(a.query) as query,
        a.usename,
        a.wait_event_type,
        a.wait_event,
        a.state,
        1 as num_backends
      FROM
        pg_stat_activity a;

  - query_name: pg_stat_statements_query
    query: |
      /* crystal-query */ SELECT
        s.userid,
        s.dbid,
        d.datname,
        s.queryid,
        lower(s.query) as query,
        s.calls,
        s.total_exec_time,
        s.total_plan_time,
        s.rows
      FROM
        pg_stat_statements s
      JOIN
        pg_database d ON s.dbid = d.oid
      WHERE
        d.datname NOT IN ('rdsadmin', 'template0', 'template1');

  - query_name: crystal_pg_stat_database_query
    query: |
      /* crystal-query */ SELECT
        datid,
        datname,
        numbackends,
        xact_commit,
        xact_rollback,
        blks_read,
        blks_hit,
        tup_returned,
        tup_fetched,
        tup_inserted,
        tup_updated,
        tup_deleted,
        conflicts,
        temp_files,
        temp_bytes,
        deadlocks,
        checksum_failures,
        blk_read_time,
        blk_write_time,
        session_time,
        active_time,
        idle_in_transaction_time,
        sessions,
        sessions_abandoned,
        sessions_fatal,
        sessions_killed,
        pg_database_size(datname) as size
      FROM
        pg_stat_database;

  - query_name: crystal_schema_disk_usage_query
    query: |
      /* crystal-query */ SELECT
          nspname AS schema_name,
          SUM(pg_total_relation_size(pg_class.oid)) AS size
      FROM
          pg_class
          JOIN pg_namespace ON relnamespace = pg_namespace.oid
      WHERE
          nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'pg_temp_1', 'pg_toast_temp_1')
      GROUP BY
          nspname;

  - query_name: crystal_table_disk_usage_query
    query: |
      /* crystal-query */ SELECT
          nspname AS schema_name,
          relname AS table_name,
          pg_total_relation_size(pg_class.oid) AS total_size,
          pg_table_size(pg_class.oid) AS table_size,
          pg_indexes_size(pg_class.oid) AS index_size,
          pg_total_relation_size(pg_class.oid) - pg_table_size(pg_class.oid) - pg_indexes_size(pg_class.oid) AS toast_size
      FROM
          pg_class
          JOIN pg_namespace ON relnamespace = pg_namespace.oid
      WHERE
          relkind = 'r'
          AND nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'pg_temp_1', 'pg_toast_temp_1');
