collector_name: postgres_vacuum
# Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
min_interval: 0s

metrics:
  - metric_name: pg_vacuum_process_count
    type: gauge
    help: 'Count of the number of active vacuum processes.'
    values: [vacuum_count]
    query: |
      SELECT COUNT(*) vacuum_count
      FROM pg_stat_activity
      WHERE (query ILIKE 'vacuum%' or query ilike 'autovacuum%')
      AND state = 'active';
