global:
  scrape_interval:      1m
  evaluation_interval:  5s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgres"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9187","localhost:9399"]
        # :9187 postgres exporter
        # :9399 sql exporter
  - job_name: "rds"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9043"]
        # :9043 rds exporter
